name: Deploy frontend

on:
  push:
    branches:
      - main
    paths:
      - pkgs/client/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - name: Change API URL
        run: |
          sed -i "3s|.*|const API_URL='${{ vars.API_URL }}'|" pkgs/client/src/main.ts
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Bundle files
        uses: oven-sh/setup-bun@v2
      - run: bun install && bun run --filter client build
      - name: Upload files
        uses: actions/upload-pages-artifact@v4
        with:
          path: './pkgs/client/dist'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4