name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - name: Change API URL
        run: |
          sed -i "1s/.*/const API_URL='${{ env.API_URL }}'/" client/main.js

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: npm
          wranglerVersion: "latest"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --assets ./client