name: Deploy frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - name: Change API URL
        run: |
          sed -i "1s|.*|const API_URL='${{ vars.API_URL }}'|" src/client/main.js
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload files
        uses: actions/upload-pages-artifact@v3
        with:
          path: './src/client/'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4